### PR TITLE
Added support for Codewars, Twitter and freeCodecamp

### PR DESCRIPTION
**Pull request by ManavMalhotra**
Signed-off-by: ManavMalhotra <manavmalhotrafrnd4u@gmail.com>

## Issue that this pull request solves

Added support for Codewars, Twitter and freeCodecamp support

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Aman-Codes** [comment]
Hi @ManavMalhotra 
Thanks for your contribution could you please create separate pr for each platform as currently the twitter api code is not working. Also if possible could we avoid using the authenticated twitter api.

**Comment by ManavMalhotra** [comment]
Hey @Aman-Codes



I got your point of creating separate PR for each platform, but now it is creating confusion to split/edit the code.

**Comment by ManavMalhotra** [comment]
@Aman-Codes Is something wrong with my code

**Comment by Aman-Codes** [comment]
Hi @ManavMalhotra thanks for your contribution. Could you please resolve the merge conflict.

**Comment by ManavMalhotra** [comment]
@Aman-Codes Please check If there is any issue

**Pull request merged**
